### ISSUE TITLE
maps.elastic.co doesn't load at all on IE11

### ISSUE THREAD

**Issue by marius-dr** [elastic/ems-file-service#59]
If you try to open the page on IE11, it shows just a blank screen. 
The following error is in the console:
```
HTML1300: Navigation occurred.
maps.elastic.co
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
maps.elastic.co
Unhandled promise rejection ReferenceError: 'fetch' is undefined
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "'fetch' is undefined",
      message: "'fetch' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'fetch' is undefined
   at Anonymous function (https://maps.elastic.co/main.bundle.js:114:530583)
   at w (https://maps.elastic.co/main.bundle.js:26:1220479)
   at Anonymous function (https://maps.elastic.co/main.bundle.js:26:1220288)
   at e[t] (https://maps.elastic.co/main.bundle.js:26:1220673)
   at r (https://maps.elastic.co/main.bundle.js:114:530085)
   at Anonymous function (https://maps.elastic.co/main.bundle.js:114:530058)
   at M (https://maps.elastic.co/main.bundle.js:26:1199119)
   at Anonymous function (https://maps.elastic.co/main.bundle.js:114:530025)
   at Anonymous function (https://maps.elastic.co/main.bundle.js:114:530801)
   at Anonymous function (https://maps.elastic.co/main.bundle.js:114:531019)",
      Symbol()_w.yjoxcvwozfd: undefined,
      Symbol()_x.yjoxcvwozfd: undefined,
      Symbol(react.async_mode)_u.yjoxcvwozsd: undefined,
      Symbol(react.call)_n.yjoxcvwozsd: undefined,
      Symbol(react.context)_t.yjoxcvwozsd: undefined,
      Symbol(react.element)_m.yjoxcvwozsd: undefined,
      Symbol(react.forward_ref)_v.yjoxcvwozsd: undefined,
      Symbol(react.fragment)_q.yjoxcvwozsd: undefined,
      Symbol(react.portal)_p.yjoxcvwozsd: undefined,
      Symbol(react.provider)_s.yjoxcvwozsd: undefined,
      Symbol(react.return)_o.yjoxcvwozsd: undefined,
      Symbol(react.strict_mode)_r.yjoxcvwozsd: undefined
   }
```

All good on Edge and the other browsers.

cc @thomasneirynck

**Comment by marius-dr** [comment]
wrong repo, brain freeze
